[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MuJoCo = "1c101251-5e0f-4746-b44c-0728d433b68a"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
